name: hullwake
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision=0.17.2
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - pillow=10.2.0
  - pyyaml=6.0.1
  - pycocotools=2.0.7
  - tqdm=4.66.2
  - pip
  - pip:
      - pytest==8.1.1
      - ruff==0.3.4
